---
title: "Multinomial Regression"
output: html_document
date: "2026-04-05"
---

```{r}
library(terra)
library(dplyr)
library(nnet)  
library(tidyr)
library(raster)
library(nnet)

root_dir <- "C:/Users/erikg/Downloads/desert_project/"
```

Working with Senegal first

Choosing smaller area for testing
```{r}
library(terra)

r <- rast("C:/Users/erikg/Downloads/desert_project/SenegalData_WithProp.tif")

# Crop by percentages
crop_by_percent <- function(r, xmin_pct = 0, xmax_pct = 1, ymin_pct = 0, ymax_pct = 1) {
  e0 <- ext(r)
  
  x0 <- e0$xmin + xmin_pct * (e0$xmax - e0$xmin)
  x1 <- e0$xmin + xmax_pct * (e0$xmax - e0$xmin)
  y0 <- e0$ymin + ymin_pct * (e0$ymax - e0$ymin)
  y1 <- e0$ymin + ymax_pct * (e0$ymax - e0$ymin)
  
  e <- ext(x0, x1, y0, y1)
  
  crop(r, e)
}

# Example: crop the bottom-right quarter of the raster
r_sub <- crop_by_percent(r, xmin_pct = .6, xmax_pct = .8, ymin_pct = .6, ymax_pct = .8)

# nevermind
r_sub <- r
```
Function for plotting land cover
```{r}
lc_color_key <- c(
  "1"  = "#05450a", 
  "2"  = "#086a10", 
  "3"  = "#54a008", 
  "4"  = "#78d203", 
  "5"  = "#009900", 
  "6"  = "#05450a", 
  "7"  = "#d68d24", 
  "8"  = "#b3a334", 
  "9"  = "#a6d96a",
  "10" = "#1a9850", 
  "11" = "#27ff87", 
  "12" = "#c24f44", 
  "13" = "#a5a5a5", 
  "14" = "#ff6d4c", 
  "15" = "#69fff8", 
  "16" = "#f5deb3", 
  "17" = "#A6CEE3", 
  "0"  = "#A6CEE3", 
  "255"= "#ffffff"
)

master_labels <- c(
  "1"  = "Evergreen Needleleaf Forest",
  "2"  = "Evergreen Broadleaf Forest",
  "3"  = "Deciduous Needleleaf Forest",
  "4"  = "Deciduous Broadleaf Forest",
  "5"  = "Mixed Forest",
  "6"  = "Closed Shrublands",
  "7"  = "Open Shrublands",
  "8"  = "Woody Savannas",
  "9"  = "Savannas",
  "10" = "Grasslands",
  "11" = "Permanent Wetlands",
  "12" = "Croplands",
  "13" = "Urban and Built-up",
  "14" = "Cropland/Natural Mosaic",
  "15" = "Permanent Snow and Ice",
  "16" = "Barren",
  "17" = "Water Bodies",
  "0"  = "Water Bodies",
  "255"= "Unclassified"
)

plot_lc <- function(r) {
  rgb_mat <- t(col2rgb(lc_color_key))
  
  ct <- cbind(
    value = as.integer(names(lc_color_key)),
    rgb_mat
  )
  
  # Converting labels
  coltab(r) <- ct
  
  # Adding colors
  levels(r) <- data.frame(
    value = as.integer(names(master_labels)),
    label = master_labels
  )
  
  plot(r)
}
```

Converting data into a table
```{r}
df <- as.data.frame(r_sub, xy = TRUE, na.rm = FALSE)

df_long <- df %>%
  pivot_longer(
    cols = -c(x, y),
    names_to = c("Variable", "Year"),
    names_sep = "_",
    values_to = "Value"
  ) %>%
  pivot_wider(
    names_from = "Variable",
    values_from = "Value"
  ) %>%
  mutate(Year = as.integer(Year))

df_long$Pop[is.na(df_long$Pop)] <- 0

df_long
```

Making transition matrix
```{r}
# filtering out under-represented land cover types
valid_classes <- df_long %>% 
  count(LandCover) %>%
  filter(n / sum(n) >= 0) %>%  # currently not active, can change to e.g. >= .05
  pull(LandCover)

df_filtered <- df_long %>%
  filter(LandCover %in% valid_classes)


# transition matrix
df_trans <- df_filtered %>%
  group_by(x, y) %>%
  arrange(Year) %>%
  mutate(LandCover_next = lead(LandCover)) %>%
  filter(!is.na(LandCover_next))

transition_matrix <- df_trans %>%
  group_by(LandCover, LandCover_next) %>%
  summarize(count = n(), .groups = "drop") %>%
  group_by(LandCover) %>%
  mutate(prob = count / sum(count)) %>%
  dplyr::select(LandCover, LandCover_next, prob) %>%
  mutate(
    LandCover = master_labels[LandCover],
    LandCover_next = master_labels[LandCover_next]
  ) %>%
  pivot_wider(names_from = LandCover_next, values_from = prob)
```

Modeling a multinomial regression
```{r}
library(rsample)
library(caret)
set.seed(2)

# prep
df_prep <- df_trans %>% mutate(
  LandCover = as.factor(LandCover),
  LandCover_next = as.factor(LandCover_next)
)

data_split <- initial_split(df_prep, prop = .99)

train <- training(data_split)
test <- testing(data_split)

# training
model <- nnet::multinom(
  LandCover_next ~ LandCover + Year + DayTemp + EVI + NDVI + NightTemp + Pop + Precip + SameStateNeighborProp,
  data = train
)

# testing
probs <- predict(model, newdata = test, type = "probs")

classes <- colnames(probs)

stochastic_preds <- apply(probs, 1, function(p) {
  sample(classes, 1, prob = p)
})

stochastic_preds <- factor(stochastic_preds, levels = levels(test$LandCover_next))

# log loss
y <- as.numeric(test$LandCover_next)
p_true <- probs[cbind(1:nrow(probs), y)]
log_loss <- -mean(log(p_true))

# confusion matrix
results <- caret::confusionMatrix(stochastic_preds, test$LandCover_next)
results
```

Modeling a dynamic bayesian model
```{r}
df_dbn <- df_long %>%
  group_by(x, y) %>%
  arrange(Year) %>%
  mutate(
    LandCover_next = lead(LandCover),
    NDVI_next = lead(NDVI),
    EVI_next = lead(EVI),
    Pop_next = lead(Pop),
    Precip_next = lead(Precip),
    DayTemp_next = lead(DayTemp),
    NightTemp_next = lead(NightTemp),
    SameStateNeighborProp = lead(SameStateNeighborProp)
  ) %>%
  ungroup() %>%
  drop_na()

# factors
df_dbn$LandCover <- as.factor(df_dbn$LandCover)
df_dbn$LandCover_next <- as.factor(df_dbn$LandCover_next)



lc_model <- multinom(
  LandCover_next ~ LandCover + NDVI + EVI + Pop + Precip + DayTemp + NightTemp,
  data = df_dbn,
  trace = FALSE
)

ndvi_model <- lm(
  NDVI_next ~ NDVI + LandCover + Precip + DayTemp,
  data = df_dbn
)

evi_model <- lm(
  EVI_next ~ EVI + LandCover + Precip + DayTemp,
  data = df_dbn
)

pop_model <- lm(
  Pop_next ~ Pop + Year,
  data = df_dbn
)

precip_model <- lm(
  Precip_next ~ Precip,
  data = df_dbn
)

daytemp_model <- lm(
  DayTemp_next ~ DayTemp,
  data = df_dbn
)

nighttemp_model <- lm(
  NightTemp_next ~ NightTemp,
  data = df_dbn
)
```


Modeling into the future
```{r}
w <- matrix(1, 3, 3)

prop_same_fun <- function(x, ...) {
  center <- x[ceiling(length(x)/2)]
  mean(x == center, na.rm = TRUE)
}

compute_neighbor_prop <- function(r_layer) {
  focal(
    r_layer,
    w = w,
    fun = prop_same_fun,
    na.policy = "omit",
    pad = TRUE
  )
}

# start from 2023
current_state <- df_long %>%
  group_by(x, y) %>%
  filter(Year == 2023) %>%
  ungroup()

# ensure factor levels match training
current_state$LandCover <- factor(
  current_state$LandCover,
  levels = levels(df_dbn$LandCover)
)

future_years <- 2024:2040 # change this
sim_list <- list()

set.seed(42)

for (yr in future_years) {
  
  current_state$Year <- yr
  
  # building environment
  current_state$NDVI <- predict(ndvi_model, newdata = current_state)
  current_state$EVI  <- predict(evi_model, newdata = current_state)
  current_state$Pop  <- predict(pop_model, newdata = current_state)
  
  current_state$Precip    <- predict(precip_model, newdata = current_state)
  current_state$DayTemp   <- predict(daytemp_model, newdata = current_state)
  current_state$NightTemp <- predict(nighttemp_model, newdata = current_state)
  
  current_state$NDVI <- pmax(pmin(current_state$NDVI, 1), -1)
  current_state$EVI  <- pmax(pmin(current_state$EVI, 1), -1)
  
  # Update land cover
  probs <- predict(lc_model, newdata = current_state, type = "probs")
  classes <- colnames(probs)
  
  next_lc <- apply(probs, 1, function(p) {
    sample(classes, 1, prob = p)
  })
  
  current_state$LandCover <- factor(next_lc, levels = classes)
  
  # rebuild raster
  r_tmp <- r_sub[[1]]
  values(r_tmp) <- NA
  
  cells <- cellFromXY(r_tmp, as.matrix(current_state[, c("x", "y")]))
  values(r_tmp)[cells] <- as.integer(as.character(current_state$LandCover))
  
  # compute neighborhood structure for THIS simulated year
  nbh <- compute_neighbor_prop(r_tmp)
  
  # back to table
  current_state$SameStateNeighborProp <- terra::values(nbh)
  
  sim_list[[as.character(yr)]] <- current_state
}

future_dbn <- bind_rows(sim_list)
```


```{r}
future_rasters <- lapply(future_years, function(yr) {
  
  df_year <- future_dbn %>% filter(Year == yr)
  
  r_out <- r_sub[[1]]  # take one layer as template
  
  # match cells
  cells <- cellFromXY(
    r_out,
    as.matrix(df_year[, c("x", "y")])
  )
  
  values(r_out) <- NA
  values(r_out)[cells] <- as.integer(as.character(df_year$LandCover))
  
  r_out
})

names(future_rasters) <- future_years

for (r in future_rasters) {
  plot_lc(r)
}

plot_lc(future_rasters[["2024"]])

levels(current_state$LandCover)
```

