---
title: "Initial_EDA"
output: html_document
---

```{r}

# Libraries
library(tidyverse)
library(terra)

```

```{r}

# Global Colors and Labels (IGBP Classes)
master_colors <- c(
  "1"  = "#05450a", # Evergreen Needleleaf
  "2"  = "#086a10", # Evergreen Broadleaf
  "3"  = "#54a008", # Deciduous Needleleaf
  "4"  = "#78d203", # Deciduous Broadleaf
  "5"  = "#009900", # Mixed Forest
  "6"  = "#05450a", # Closed Shrublands
  "7"  = "#dcd159", # Open Shrublands
  "8"  = "#dade48", # Woody Savannas
  "9"  = "#fbff13", # Savannas
  "10" = "#b6ff05", # Grasslands
  "11" = "#27ff87", # Permanent Wetlands
  "12" = "#c24f44", # Croplands
  "13" = "#a5a5a5", # Urban and Built-up
  "14" = "#ff6d4c", # Cropland/Natural Mosaic
  "15" = "#69fff8", # Permanent Snow and Ice
  "16" = "#f9ffa4", # Barren
  "17" = "#A6CEE3", # Water Bodies
  "0"  = "#A6CEE3", # Alternative Water Code
  "255"= "#ffffff"  # Unclassified
)

master_labels <- c(
  "1"  = "Evergreen Needleleaf Forest",
  "2"  = "Evergreen Broadleaf Forest",
  "3"  = "Deciduous Needleleaf Forest",
  "4"  = "Deciduous Broadleaf Forest",
  "5"  = "Mixed Forest",
  "6"  = "Closed Shrublands",
  "7"  = "Open Shrublands",
  "8"  = "Woody Savannas",
  "9"  = "Savannas",
  "10" = "Grasslands",
  "11" = "Permanent Wetlands",
  "12" = "Croplands",
  "13" = "Urban and Built-up",
  "14" = "Cropland/Natural Mosaic",
  "15" = "Permanent Snow and Ice",
  "16" = "Barren",
  "17" = "Water Bodies",
  "0"  = "Water Bodies",
  "255"= "Unclassified"
)

```

```{r}

# Lake Chad Land Cover (h19v07): 2001, 2007, 2024

# 2001
CL_2001 <- sds("Data/LandCover.h19v07/LandCover.h19v07.2001.hdf") # Change file path based on user
CL_2001_DF <- as.data.frame(CL_2001[1], xy = TRUE)

CL_2001_PLOT <- ggplot(CL_2001_DF, aes(x = x, y = y)) +
  geom_raster(aes(fill = as.factor(Land_Cover_Type_1))) +
  scale_fill_manual(
    values = master_colors, 
    labels = master_labels,
    name = "MODIS IGBP Legend",
    drop = TRUE # Set to FALSE to keep the legend consistent across different datasets
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Land Cover Classification (2001)")

# 2007
CL_2007 <- sds("Data/LandCover.h19v07/LandCover.h19v07.2007.hdf") # Change file path based on user
CL_2007_DF <- as.data.frame(CL_2007[1], xy = TRUE)

CL_2007_PLOT <- ggplot(CL_2007_DF, aes(x = x, y = y)) +
  geom_raster(aes(fill = as.factor(Land_Cover_Type_1))) +
  scale_fill_manual(
    values = master_colors, 
    labels = master_labels,
    name = "MODIS IGBP Legend",
    drop = TRUE # Set to FALSE to keep the legend consistent across different datasets
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Land Cover Classification (2007)")

# 2024
CL_2024 <- sds("Data/LandCover.h19v07/LandCover.h19v07.2024.hdf") # Change file path based on user
CL_2024_DF <- as.data.frame(CL_2024[1], xy = TRUE)

CL_2024_PLOT <- ggplot(CL_2024_DF, aes(x = x, y = y)) +
  geom_raster(aes(fill = as.factor(Land_Cover_Type_1))) +
  scale_fill_manual(
    values = master_colors, 
    labels = master_labels,
    name = "MODIS IGBP Legend",
    drop = TRUE # Set to FALSE to keep the legend consistent across different datasets
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Land Cover Classification (2024)")

# Export Plots to PNG
ggsave("Images/CL_2001.png", plot = CL_2001_PLOT)
ggsave("Images/CL_2007.png", plot = CL_2007_PLOT)
ggsave("Images/CL_2024.png", plot = CL_2024_PLOT)

```

```{r}

# Lake Chad Vegetation Index (h19v07): 2001.08, 2007.08, 2024.08

# 2001.08
CV_2001_08 <- sds("Data/Vegetation.h19v07/Vegetation.h19v07.2001.08.hdf") # Change file path based on user
CV_2001_08_DF <- as.data.frame(CV_2001_08[2], xy = TRUE)

CV_2001_08_PLOT <- ggplot(CV_2001_08_DF, aes(x = x, y = y, fill = `1 km monthly EVI`)) +
  geom_raster() +
  scale_fill_viridis_c(
    name = "EVI",
    option = "D"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Vegetation Index (2001/08)")

# 2007.08
CV_2007_08 <- sds("Data/Vegetation.h19v07/Vegetation.h19v07.2007.08.hdf") # Change file path based on user
CV_2007_08_DF <- as.data.frame(CV_2007_08[2], xy = TRUE)

CV_2007_08_PLOT <- ggplot(CV_2007_08_DF, aes(x = x, y = y, fill = `1 km monthly EVI`)) +
  geom_raster() +
  scale_fill_viridis_c(
    name = "EVI",
    option = "D"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Vegetation Index (2007/08)")

# 2024.08
CV_2024_08 <- sds("Data/Vegetation.h19v07/Vegetation.h19v07.2024.08.hdf") # Change file path based on user
CV_2024_08_DF <- as.data.frame(CV_2024_08[2], xy = TRUE)

CV_2024_08_PLOT <- ggplot(CV_2024_08_DF, aes(x = x, y = y, fill = `1 km monthly EVI`)) +
  geom_raster() +
  scale_fill_viridis_c(
    name = "EVI",
    option = "D"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Vegetation Index (2024/08)")

# Export Plots to PNG
ggsave("Images/CV_2001_08.png", plot = CV_2001_08_PLOT)
ggsave("Images/CV_2007_08.png", plot = CV_2007_08_PLOT)
ggsave("Images/CV_2024_08.png", plot = CV_2024_08_PLOT)

```

```{r}

# Lake Chad Land Surface Temperature (h19v07): 2001.08, 2007.08, 2024.08

# 2001.08
CT_2001_08 <- sds("Data/Temperature.h19v07/Temperature.h19v07.2001.08.hdf") # Change file path based on user
CT_2001_08_DF <- as.data.frame(CT_2001_08[1], xy = TRUE)

CT_2001_08_PLOT <- ggplot(CT_2001_08_DF, aes(x = x, y = y, fill = `monthly daytime 6km grid Land-surface Temperature`)) +
  geom_raster() +
  scale_fill_viridis_c(
    option = "inferno",
    name = "LST (K)"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Temperature (2001/08)")

# 2007.08
CT_2007_08 <- sds("Data/Temperature.h19v07/Temperature.h19v07.2007.08.hdf") # Change file path based on user
CT_2007_08_DF <- as.data.frame(CT_2007_08[1], xy = TRUE)

CT_2007_08_PLOT <- ggplot(CT_2007_08_DF, aes(x = x, y = y, fill = `monthly daytime 6km grid Land-surface Temperature`)) +
  geom_raster() +
  scale_fill_viridis_c(
    option = "inferno",
    name = "LST (K)"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Temperature (2007/08)")

# 2024.08
CT_2024_08 <- sds("Data/Temperature.h19v07/Temperature.h19v07.2024.08.hdf") # Change file path based on user
CT_2024_08_DF <- as.data.frame(CT_2024_08[1], xy = TRUE)

CT_2024_08_PLOT <- ggplot(CT_2024_08_DF, aes(x = x, y = y, fill = `monthly daytime 6km grid Land-surface Temperature`)) +
  geom_raster() +
  scale_fill_viridis_c(
    option = "inferno",
    name = "LST (K)"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  coord_equal() +
  theme_bw() +
  labs(title = "Chad Temperature (2024/08)")

# Export Plots to PNG
ggsave("Images/CT_2001_08.png", plot = CT_2001_08_PLOT)
ggsave("Images/CT_2007_08.png", plot = CT_2007_08_PLOT)
ggsave("Images/CT_2024_08.png", plot = CT_2024_08_PLOT)

```





