---
title: "Snapshots"
output: html_document
---

# Libraries

```{r}

# Libraries
library(tidyverse)
library(terra)

```

# Global Variables
```{r}

# Global Colors and Labels (IGBP Classes)
master_colors <- c(
  "1"  = "#05450a", # Evergreen Needleleaf
  "2"  = "#086a10", # Evergreen Broadleaf
  "3"  = "#54a008", # Deciduous Needleleaf
  "4"  = "#78d203", # Deciduous Broadleaf
  "5"  = "#009900", # Mixed Forest
  "6"  = "#05450a", # Closed Shrublands
  "7"  = "#dcd159", # Open Shrublands
  "8"  = "#dade48", # Woody Savannas
  "9"  = "#fbff13", # Savannas
  "10" = "#b6ff05", # Grasslands
  "11" = "#27ff87", # Permanent Wetlands
  "12" = "#c24f44", # Croplands
  "13" = "#a5a5a5", # Urban and Built-up
  "14" = "#ff6d4c", # Cropland/Natural Mosaic
  "15" = "#69fff8", # Permanent Snow and Ice
  "16" = "#f9ffa4", # Barren
  "17" = "#A6CEE3", # Water Bodies
  "0"  = "#A6CEE3", # Alternative Water Code
  "255"= "#ffffff"  # Unclassified
)

master_labels <- c(
  "1"  = "Evergreen Needleleaf Forest",
  "2"  = "Evergreen Broadleaf Forest",
  "3"  = "Deciduous Needleleaf Forest",
  "4"  = "Deciduous Broadleaf Forest",
  "5"  = "Mixed Forest",
  "6"  = "Closed Shrublands",
  "7"  = "Open Shrublands",
  "8"  = "Woody Savannas",
  "9"  = "Savannas",
  "10" = "Grasslands",
  "11" = "Permanent Wetlands",
  "12" = "Croplands",
  "13" = "Urban and Built-up",
  "14" = "Cropland/Natural Mosaic",
  "15" = "Permanent Snow and Ice",
  "16" = "Barren",
  "17" = "Water Bodies",
  "0"  = "Water Bodies",
  "255"= "Unclassified"
)

```

# Functions 

```{r}

# Plotting Functions

## Land Cover Function
plot_landcover_snapshot <- function(file_path, title_label) {
  # 1. Load the SDS and pull the first subdataset
  s <- sds(file_path)
  rast_data <- s[1]
  
  # 2. Convert to Data Frame
  df <- as.data.frame(rast_data, xy = TRUE)
  
  # 3. Ensure the Class column is correctly named and factorized
  colnames(df)[3] <- "IGBP_Class"
  df$IGBP_Class <- factor(df[[3]], levels = names(master_labels))
  
  # 4. Generate the Plot
  ggplot(df, aes(x = x, y = y, fill = IGBP_Class)) +
    geom_raster() +
    scale_fill_manual(
      values = master_colors,
      labels = master_labels,
      name = "IGBP Class",
      drop = TRUE,
      na.translate = FALSE
    ) + 
    coord_equal() +
    theme_bw() + 
    labs(
      title = title_label,
      subtitle = "Coordinate System: MODIS Sinusoidal (Native Meters)",
      x = "Easting (m)", 
      y = "Northing (m)"
    ) +
    theme(
      legend.position = "right", 
      legend.text = element_text(size = 8),
      plot.title = element_text(face = "bold")
    ) + 
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0))
}

## Vegetation Index Function
plot_vegetation_snapshot <- function(file_path, title_label) {
  # 1. Load the SDS and pull the second subdataset
  s <- sds(file_path)
  rast_data <- s[2]
  
  # 2. Convert to Data Frame
  df <- as.data.frame(rast_data, xy = TRUE)
  
  
  # 3. Ensure the EVI column is correctly named and normalized
  colnames(df)[3] <- "EVI"
  df$EVI <- df$EVI * 0.00000001

  # 4. Generate the Plot
  ggplot(df, aes(x = x, y = y, fill = EVI)) +
    geom_raster() +
    scale_fill_viridis_c(
      option = "mako", 
      name = "EVI",
      na.value = "transparent"
    ) +
    coord_equal() +
    theme_bw() +
    labs(
      title = title_label,
      subtitle = "Coordinate System: MODIS Sinusoidal (Native Meters)",
      x = "Easting (m)", 
      y = "Northing (m)"
    ) +
    theme(
      legend.position = "right", 
      legend.text = element_text(size = 8),
      plot.title = element_text(face = "bold")
    ) + 
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0))
}

## Land Surface Temperature
plot_temp_snapshot <- function(file_path, title_label) {
  # 1. Load the SDS and pull the first subdataset
  s <- sds(file_path)
  rast_data <- s[1] 
  
  # 2. Convert to dataframe
  df <- as.data.frame(rast_data, xy = TRUE)
  
  # 3. Ensure the Day Temp column is correctly named and turned into Celsius
  colnames(df)[3] <- "Day_Temp_K"
  df$Day_Temp_C <- (df$Day_Temp) - 273.15
  
  # 4. Generate the Plot
  ggplot(df, aes(x = x, y = y, fill = Day_Temp_C)) +
    geom_raster() +
    scale_fill_viridis_c(
    option = "inferno",
    name = "Temp °C",
    ) +
    coord_equal() +
    theme_bw() +
    labs(
      title = title_label,
      subtitle = "Coordinate System: MODIS Sinusoidal (Native Meters)",
      x = "Easting (m)", 
      y = "Northing (m)"
    ) +
    theme(
      legend.position = "right", 
      legend.text = element_text(size = 8),
      plot.title = element_text(face = "bold")
    ) + 
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0))
}

```

# Initial Snapshots 

## Chad

```{r}

# Chad Land Cover (h19v07): 2001, 2007, 2024

## 2001
CL_2001 <- "Data/LandCover.h19v07/LandCover.h19v07.2001.hdf"

CL_2001_PLOT <- plot_landcover_snapshot(CL_2001, "Lake Chad Land Classification: 2001")

# 2007
CL_2007 <- "Data/LandCover.h19v07/LandCover.h19v07.2007.hdf"

CL_2007_PLOT <- plot_landcover_snapshot(CL_2007, "Lake Chad Land Classification: 2007")

## 2024
CL_2024 <- "Data/LandCover.h19v07/LandCover.h19v07.2024.hdf"

CL_2024_PLOT <- plot_landcover_snapshot(CL_2024, "Lake Chad Land Classification: 2024")

## Save Snapshots
ggsave("Images/CL_2001.png", plot = CL_2001_PLOT)
ggsave("Images/CL_2007.png", plot = CL_2007_PLOT)
ggsave("Images/CL_2024.png", plot = CL_2024_PLOT)

```

```{r}

# Chad Vegetation Index (h19v07): Aug 2001, 2007, 2024

## AUG 2001
CV_2001_08 <- "Data/Vegetation.h19v07/Vegetation.h19v07.2001.08.hdf"

CV_2001_08_PLOT <- plot_vegetation_snapshot(CV_2001_08, "Lake Chad EVI: Aug 2001")

## AUG 2007
CV_2007_08 <- "Data/Vegetation.h19v07/Vegetation.h19v07.2007.08.hdf"

CV_2007_08_PLOT <- plot_vegetation_snapshot(CV_2007_08, "Lake Chad EVI: Aug 2007")

## AUG 2024
CV_2024_08 <- "Data/Vegetation.h19v07/Vegetation.h19v07.2024.08.hdf"

CV_2024_08_PLOT <- plot_vegetation_snapshot(CV_2024_08, "Lake Chad EVI: Aug 2024")

## Save Snapshots
ggsave("Images/CV_2001_08.png", plot = CV_2001_08_PLOT)
ggsave("Images/CV_2007_08.png", plot = CV_2007_08_PLOT)
ggsave("Images/CV_2024_08.png", plot = CV_2024_08_PLOT)

```

```{r}

# Chad Land Surface Temperature (h19v07): 2001, 2007, 2024

## AUG 2001
CT_2001_08 <- "Data/Temperature.h19v07/Temperature.h19v07.2001.08.hdf"

CT_2001_08_PLOT <- plot_temp_snapshot(CT_2001_08, "Lake Chad LST: Aug 2001")

## AUG 2007
CT_2007_08 <- "Data/Temperature.h19v07/Temperature.h19v07.2007.08.hdf"

CT_2007_08_PLOT <- plot_temp_snapshot(CT_2007_08, "Lake Chad LST: Aug 2007")

## AUG 2024
CT_2024_08 <- "Data/Temperature.h19v07/Temperature.h19v07.2024.08.hdf"

CT_2024_08_PLOT <- plot_temp_snapshot(CT_2024_08, "Lake Chad LST: Aug 2024")

## Save Snapshots
ggsave("Images/CT_2001_08.png", plot = CT_2001_08_PLOT)
ggsave("Images/CT_2007_08.png", plot = CT_2007_08_PLOT)
ggsave("Images/CT_2024_08.png", plot = CT_2024_08_PLOT)

```





